<?php
/**
 * Created by PhpStorm.
 * User: hulj
 * Date: 2016/6/20
 * Time: 10:55
 */
namespace app\models;
use yii\base\Model;

class EntryForm extends Model{
    public $name;
    public $email;
    public $phone;

    public function rules()
    {
        return [
            [['name','email','phone'],'required'],
            ['email','email']
        ]; // TODO: Change the autogenerated stub
    }
}


?>